In [1]:
import pandas as pd
import numpy as np

In [3]:
books = pd.read_csv('C:\\Users\\rwang\\OneDrive - Wallick Communities\\Desktop\\Reports\\Learn Python\\Recommender System\\data\\BX-Books.csv', sep=';', on_bad_lines='skip', encoding='latin-1')

C:\Users\rwang\AppData\Local\Temp\ipykernel_30092\3293462930.py:1: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('C:\\Users\\rwang\\OneDrive - Wallick Communities\\Desktop\\Reports\\Learn Python\\Recommender System\\data\\BX-Books.csv', sep=';', on_bad_lines='skip', encoding='latin-1')

In [5]:
ratings= pd.read_csv('C:\\Users\\rwang\\OneDrive - Wallick Communities\\Desktop\\Reports\\Learn Python\\Recommender System\\data\\BX-Book-Ratings.csv', sep=';', on_bad_lines='skip', encoding='latin-1')

In [7]:
books.head(10)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
5,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...
6,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,Berkley Publishing Group,http://images.amazon.com/images/P/0425176428.0...,http://images.amazon.com/images/P/0425176428.0...,http://images.amazon.com/images/P/0425176428.0...
7,0671870432,PLEADING GUILTY,Scott Turow,1993,Audioworks,http://images.amazon.com/images/P/0671870432.0...,http://images.amazon.com/images/P/0671870432.0...,http://images.amazon.com/images/P/0671870432.0...
8,0679425608,Under the Black Flag: The Romance and the Real...,David Cordingly,1996,Random House,http://images.amazon.com/images/P/0679425608.0...,http://images.amazon.com/images/P/0679425608.0...,http://images.amazon.com/images/P/0679425608.0...
9,074322678X,Where You'll Find Me: And Other Stories,Ann Beattie,2002,Scribner,http://images.amazon.com/images/P/074322678X.0...,http://images.amazon.com/images/P/074322678X.0...,http://images.amazon.com/images/P/074322678X.0...

In [ ]:
books['ISBN'].nunique()

271360

In [6]:
ratings.head(10)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6
5   276733  2080674722            0
6   276736  3257224281            8
7   276737  0600570967            6
8   276744  038550120X            7
9   276745   342310538           10

In [12]:
ratings_with_books = ratings.merge(books, on='ISBN')
ratings_with_books

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276704,0876044011,0,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,1998,A.R.E. Press (Association of Research &amp; Enlig,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...
1031132,276704,1563526298,9,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,2000,Longstreet Press,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...
1031133,276706,0679447156,0,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,1997,Alfred A. Knopf,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...
1031134,276709,0515107662,10,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,1996,Jove Books,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...
1031135,276721,0590442449,10,Fourth Grade Rats,Jerry Spinelli,1996,Scholastic,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...

In [16]:
number_ratings = ratings_with_books.groupby('Book-Title').count().reset_index()
number_ratings['User-ID'].nunique()

377

In [11]:
number_ratings

,Book-Title,User-ID,ISBN,Book-Rating,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,A Light in the Storm: The Civil War Diary of ...,4,4,4,4,4,4,4,4,4
1,Always Have Popsicles,1,1,1,1,1,1,1,1,1
2,Apple Magic (The Collector's series),1,1,1,1,1,1,1,1,1
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,1,1,1,1,1,1,1,1
4,Beyond IBM: Leadership Marketing and Finance ...,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...
241066,Ã?Â?lpiraten.,2,2,2,2,2,2,2,2,2
241067,Ã?Â?rger mit Produkt X. Roman.,4,4,4,4,4,4,4,4,4
241068,Ã?Â?sterlich leben.,1,1,1,1,1,1,1,1,1
241069,Ã?Â?stlich der Berge.,3,3,3,3,3,3,3,3,3
241070,Ã?Â?thique en toc,2,2,2,2,2,2,2,2,2

In [19]:
ratings_with_books['User-ID'].nunique()

92106

In [18]:
ratings_with_books['Book-Title'].nunique()

241071

In [ ]:
ratings_with_books['Book-Title'].value_counts()

Book-Title
Wild Animus                                                2502
The Lovely Bones: A Novel                                  1295
The Da Vinci Code                                           898
A Painted House                                             838
The Nanny Diaries: A Novel                                  828
                                                           ...
Death Crosses the Border                                      1
Jazz Funeral: A Skip Langdon Novel                            1
Triplet Trouble and the Class Trip (Triplet Trouble)          1
A Desert of Pure Feeling (Vintage Contemporaries)             1
Perplexing Lateral Thinking Puzzles: Scholastic Edition       1
Name: count, Length: 241071, dtype: int64

In [ ]:
ratings_with_books['Book-Title'].value_counts()>=50

Book-Title
Wild Animus                                                 True
The Lovely Bones: A Novel                                   True
The Da Vinci Code                                           True
A Painted House                                             True
The Nanny Diaries: A Novel                                  True
                                                           ...
Death Crosses the Border                                   False
Jazz Funeral: A Skip Langdon Novel                         False
Triplet Trouble and the Class Trip (Triplet Trouble)       False
A Desert of Pure Feeling (Vintage Contemporaries)          False
Perplexing Lateral Thinking Puzzles: Scholastic Edition    False
Name: count, Length: 241071, dtype: bool

In [20]:
# Only keep users who rated at least X books
min_ratings_user = 50
active_users = ratings_with_books['User-ID'].value_counts()
active_users = active_users[active_users >= min_ratings_user].index

# Only keep books that have at least X ratings
min_ratings_book = 50
popular_books = ratings_with_books['Book-Title'].value_counts()
popular_books = popular_books[popular_books >= min_ratings_book].index

# Filter the dataframe
filtered = ratings_with_books[
    (ratings_with_books['User-ID'].isin(active_users)) &
    (ratings_with_books['Book-Title'].isin(popular_books))
]

print("Users:", filtered['User-ID'].nunique())
print("Books:", filtered['Book-Title'].nunique())

# Now pivot — much smaller
book_pivot = filtered.pivot_table(
    columns='User-ID',
    index='Book-Title',
    values='Book-Rating'
)

Users: 3019
Books: 2444

In [21]:
book_pivot

User-ID,243,254,507,638,643,741,882,929,1025,1211,...,277928,277965,278026,278137,278144,278188,278418,278582,278633,278843
Book-Title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16 Lighthouse Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1984,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010: Odyssey Two,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\Surely You're Joking, Mr. Feynman!\"": Adventures of a Curious Character""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
stardust,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
from scipy.sparse import csr_matrix

book_sparse = csr_matrix(book_pivot.fillna(0))

In [26]:
book_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 50904 stored elements and shape (2444, 3019)>

In [28]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(metric='cosine', algorithm='brute')
model.fit(book_sparse)

NearestNeighbors(algorithm='brute', metric='cosine')

In [30]:
distance,suggestion = model.kneighbors(book_pivot.iloc[237].values.reshape(1,-1),n_neighbors=6)

In [48]:
suggestion

array([[ 237, 1477, 1787, 1284, 1364,   56]])

In [54]:
book_pivot.index[suggestion[0]]

Index(['Beloved (Plume Contemporary Fiction)', 'Second Wind',
       'The Color of Water: A Black Man's Tribute to His White Mother',
       'Paradise Lost', 'Privileged Information', 'A Pirate Looks at Fifty'],
      dtype='str', name='Book-Title')

In [40]:
book_name = [book_pivot.index[book] for book in suggestion]

In [44]:
url_list = []
for name in book_name[0]:
    ids = np.where(ratings_with_books['Book-Title'] == name)[0][0]
    url = ratings_with_books.iloc[ids]['Image-URL-M']
    url_list.append(url)

In [45]:
url_list

['http://images.amazon.com/images/P/0452264464.01.MZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0515129232.01.MZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/1573225789.01.MZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0380804697.01.MZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0786013567.01.MZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0449223345.01.MZZZZZZZ.jpg']

In [47]:
import pickle
pickle.dump(model, open('artifacts/model.pkl', 'wb'))
pickle.dump(book_name, open('artifacts/book_name.pkl', 'wb'))
pickle.dump(ratings_with_books, open('artifacts/ratings_with_books.pkl', 'wb'))
pickle.dump(book_pivot, open('artifacts/book_pivot.pkl', 'wb'))

Testing Model

In [57]:
def recommend_book(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distance,suggestion = model.kneighbors(book_pivot.iloc[book_id].values.reshape(1,-1),n_neighbors=6)
    
    for j in book_pivot.index[suggestion[0]]:
        if j == book_name:
            print(f"Because you read {book_name}")
            print("The suggestion books are: \n")
        else:
            print(j)

In [58]:
book_name = "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))"
recommend_book(book_name)

Because you read Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))
The suggestion books are:

Harry Potter and the Chamber of Secrets (Book 2)
Harry Potter and the Prisoner of Azkaban (Book 3)
Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Order of the Phoenix (Book 5)
Secrets